//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Ce code source a été automatiquement généré par xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class eSummaryResult {
    
    private eSummaryResultDocumentSummarySet[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DocumentSummarySet", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public eSummaryResultDocumentSummarySet[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class eSummaryResultDocumentSummarySet {
    
    private string dbBuildField;
    
    private eSummaryResultDocumentSummarySetDocumentSummary[] documentSummaryField;
    
    private string statusField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DbBuild {
        get {
            return this.dbBuildField;
        }
        set {
            this.dbBuildField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DocumentSummary", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public eSummaryResultDocumentSummarySetDocumentSummary[] DocumentSummary {
        get {
            return this.documentSummaryField;
        }
        set {
            this.documentSummaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class eSummaryResultDocumentSummarySetDocumentSummary {
    
    private string pubDateField;
    
    private string ePubDateField;
    
    private string sourceField;
    
    private string lastAuthorField;
    
    private string titleField;
    
    private string sortTitleField;
    
    private string volumeField;
    
    private string issueField;
    
    private string pagesField;
    
    private string nlmUniqueIDField;
    
    private string iSSNField;
    
    private string eSSNField;
    
    private string recordStatusField;
    
    private string pubStatusField;
    
    private string referencesField;
    
    private string pmcRefCountField;
    
    private string fullJournalNameField;
    
    private string eLocationIDField;
    
    private string docTypeField;
    
    private string srcContribListField;
    
    private string bookTitleField;
    
    private string mediumField;
    
    private string editionField;
    
    private string publisherLocationField;
    
    private string publisherNameField;
    
    private string srcDateField;
    
    private string reportNumberField;
    
    private string availableFromURLField;
    
    private string locationLabelField;
    
    private string docContribListField;
    
    private string docDateField;
    
    private string bookNameField;
    
    private string chapterField;
    
    private string sortPubDateField;
    
    private string sortFirstAuthorField;
    
    private string vernacularTitleField;
    
    private eSummaryResultDocumentSummarySetDocumentSummaryAuthorsAuthor[][] authorsField;
    
    private eSummaryResultDocumentSummarySetDocumentSummaryLang[] langField;
    
    private eSummaryResultDocumentSummarySetDocumentSummaryPubTypeFlag[][] pubTypeField;
    
    private eSummaryResultDocumentSummarySetDocumentSummaryArticleIdsArticleId[][] articleIdsField;
    
    private eSummaryResultDocumentSummarySetDocumentSummaryHistoryPubMedPubDate[][] historyField;
    
    private eSummaryResultDocumentSummarySetDocumentSummaryAttributes[] attributesField;
    
    private string uidField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PubDate {
        get {
            return this.pubDateField;
        }
        set {
            this.pubDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string EPubDate {
        get {
            return this.ePubDateField;
        }
        set {
            this.ePubDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Source {
        get {
            return this.sourceField;
        }
        set {
            this.sourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LastAuthor {
        get {
            return this.lastAuthorField;
        }
        set {
            this.lastAuthorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SortTitle {
        get {
            return this.sortTitleField;
        }
        set {
            this.sortTitleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Volume {
        get {
            return this.volumeField;
        }
        set {
            this.volumeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Issue {
        get {
            return this.issueField;
        }
        set {
            this.issueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Pages {
        get {
            return this.pagesField;
        }
        set {
            this.pagesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NlmUniqueID {
        get {
            return this.nlmUniqueIDField;
        }
        set {
            this.nlmUniqueIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ISSN {
        get {
            return this.iSSNField;
        }
        set {
            this.iSSNField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ESSN {
        get {
            return this.eSSNField;
        }
        set {
            this.eSSNField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RecordStatus {
        get {
            return this.recordStatusField;
        }
        set {
            this.recordStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PubStatus {
        get {
            return this.pubStatusField;
        }
        set {
            this.pubStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string References {
        get {
            return this.referencesField;
        }
        set {
            this.referencesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PmcRefCount {
        get {
            return this.pmcRefCountField;
        }
        set {
            this.pmcRefCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FullJournalName {
        get {
            return this.fullJournalNameField;
        }
        set {
            this.fullJournalNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ELocationID {
        get {
            return this.eLocationIDField;
        }
        set {
            this.eLocationIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DocType {
        get {
            return this.docTypeField;
        }
        set {
            this.docTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SrcContribList {
        get {
            return this.srcContribListField;
        }
        set {
            this.srcContribListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BookTitle {
        get {
            return this.bookTitleField;
        }
        set {
            this.bookTitleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Medium {
        get {
            return this.mediumField;
        }
        set {
            this.mediumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Edition {
        get {
            return this.editionField;
        }
        set {
            this.editionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PublisherLocation {
        get {
            return this.publisherLocationField;
        }
        set {
            this.publisherLocationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PublisherName {
        get {
            return this.publisherNameField;
        }
        set {
            this.publisherNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SrcDate {
        get {
            return this.srcDateField;
        }
        set {
            this.srcDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ReportNumber {
        get {
            return this.reportNumberField;
        }
        set {
            this.reportNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AvailableFromURL {
        get {
            return this.availableFromURLField;
        }
        set {
            this.availableFromURLField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LocationLabel {
        get {
            return this.locationLabelField;
        }
        set {
            this.locationLabelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DocContribList {
        get {
            return this.docContribListField;
        }
        set {
            this.docContribListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DocDate {
        get {
            return this.docDateField;
        }
        set {
            this.docDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BookName {
        get {
            return this.bookNameField;
        }
        set {
            this.bookNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Chapter {
        get {
            return this.chapterField;
        }
        set {
            this.chapterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SortPubDate {
        get {
            return this.sortPubDateField;
        }
        set {
            this.sortPubDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SortFirstAuthor {
        get {
            return this.sortFirstAuthorField;
        }
        set {
            this.sortFirstAuthorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string VernacularTitle {
        get {
            return this.vernacularTitleField;
        }
        set {
            this.vernacularTitleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Author", typeof(eSummaryResultDocumentSummarySetDocumentSummaryAuthorsAuthor), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public eSummaryResultDocumentSummarySetDocumentSummaryAuthorsAuthor[][] Authors {
        get {
            return this.authorsField;
        }
        set {
            this.authorsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Lang", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public eSummaryResultDocumentSummarySetDocumentSummaryLang[] Lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("flag", typeof(eSummaryResultDocumentSummarySetDocumentSummaryPubTypeFlag), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public eSummaryResultDocumentSummarySetDocumentSummaryPubTypeFlag[][] PubType {
        get {
            return this.pubTypeField;
        }
        set {
            this.pubTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ArticleId", typeof(eSummaryResultDocumentSummarySetDocumentSummaryArticleIdsArticleId), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public eSummaryResultDocumentSummarySetDocumentSummaryArticleIdsArticleId[][] ArticleIds {
        get {
            return this.articleIdsField;
        }
        set {
            this.articleIdsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("PubMedPubDate", typeof(eSummaryResultDocumentSummarySetDocumentSummaryHistoryPubMedPubDate), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public eSummaryResultDocumentSummarySetDocumentSummaryHistoryPubMedPubDate[][] History {
        get {
            return this.historyField;
        }
        set {
            this.historyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Attributes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public eSummaryResultDocumentSummarySetDocumentSummaryAttributes[] Attributes {
        get {
            return this.attributesField;
        }
        set {
            this.attributesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uid {
        get {
            return this.uidField;
        }
        set {
            this.uidField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class eSummaryResultDocumentSummarySetDocumentSummaryAuthorsAuthor {
    
    private string nameField;
    
    private string authTypeField;
    
    private string clusterIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AuthType {
        get {
            return this.authTypeField;
        }
        set {
            this.authTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ClusterID {
        get {
            return this.clusterIDField;
        }
        set {
            this.clusterIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class eSummaryResultDocumentSummarySetDocumentSummaryLang {
    
    private string stringField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string @string {
        get {
            return this.stringField;
        }
        set {
            this.stringField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class eSummaryResultDocumentSummarySetDocumentSummaryPubTypeFlag {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class eSummaryResultDocumentSummarySetDocumentSummaryArticleIdsArticleId {
    
    private string idTypeField;
    
    private string idTypeNField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IdType {
        get {
            return this.idTypeField;
        }
        set {
            this.idTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IdTypeN {
        get {
            return this.idTypeNField;
        }
        set {
            this.idTypeNField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class eSummaryResultDocumentSummarySetDocumentSummaryHistoryPubMedPubDate {
    
    private string pubStatusField;
    
    private string dateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PubStatus {
        get {
            return this.pubStatusField;
        }
        set {
            this.pubStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class eSummaryResultDocumentSummarySetDocumentSummaryAttributes {
    
    private string flagField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string flag {
        get {
            return this.flagField;
        }
        set {
            this.flagField = value;
        }
    }
}
