using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Serialization;

namespace SymptomsEval
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     Ce code a été généré par un outil.
    //     Version du runtime :4.0.30319.42000
    //
    //     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
    //     le code est régénéré.
    // </auto-generated>
    //------------------------------------------------------------------------------

    using System.Xml.Serialization;

    // 
    // Ce code source a été automatiquement généré par xsd, Version=4.6.1055.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public partial class Name
    {

        private string langField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string lang
        {
            get
            {
                return this.langField;
            }
            set
            {
                this.langField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class JDBOR
    {

        private JDBORDisorderList[] disorderListField;

        private string dateField;

        private string versionField;

        private string copyrightField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DisorderList", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public JDBORDisorderList[] DisorderList
        {
            get
            {
                return this.disorderListField;
            }
            set
            {
                this.disorderListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string copyright
        {
            get
            {
                return this.copyrightField;
            }
            set
            {
                this.copyrightField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class JDBORDisorderList
    {

        private JDBORDisorderListDisorder[] disorderField;

        private string countField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Disorder", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public JDBORDisorderListDisorder[] Disorder
        {
            get
            {
                return this.disorderField;
            }
            set
            {
                this.disorderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string count
        {
            get
            {
                return this.countField;
            }
            set
            {
                this.countField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class JDBORDisorderListDisorder
    {

        private string orphaNumberField;

        private Name[] nameField;

        private JDBORDisorderListDisorderHPODisorderAssociationList[] hPODisorderAssociationListField;

        private string idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OrphaNumber
        {
            get
            {
                return this.orphaNumberField;
            }
            set
            {
                this.orphaNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Name", IsNullable = true)]
        public Name[] Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("HPODisorderAssociationList", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public JDBORDisorderListDisorderHPODisorderAssociationList[] HPODisorderAssociationList
        {
            get
            {
                return this.hPODisorderAssociationListField;
            }
            set
            {
                this.hPODisorderAssociationListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class JDBORDisorderListDisorderHPODisorderAssociationList
    {

        private JDBORDisorderListDisorderHPODisorderAssociationListHPODisorderAssociation[] hPODisorderAssociationField;

        private string countField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("HPODisorderAssociation", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public JDBORDisorderListDisorderHPODisorderAssociationListHPODisorderAssociation[] HPODisorderAssociation
        {
            get
            {
                return this.hPODisorderAssociationField;
            }
            set
            {
                this.hPODisorderAssociationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string count
        {
            get
            {
                return this.countField;
            }
            set
            {
                this.countField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class JDBORDisorderListDisorderHPODisorderAssociationListHPODisorderAssociation
    {

        private JDBORDisorderListDisorderHPODisorderAssociationListHPODisorderAssociationHPO[] hPOField;

        private JDBORDisorderListDisorderHPODisorderAssociationListHPODisorderAssociationHPOFrequency[] hPOFrequencyField;

        private JDBORDisorderListDisorderHPODisorderAssociationListHPODisorderAssociationDiagnosticCriteria[] diagnosticCriteriaField;

        private string idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("HPO", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public JDBORDisorderListDisorderHPODisorderAssociationListHPODisorderAssociationHPO[] HPO
        {
            get
            {
                return this.hPOField;
            }
            set
            {
                this.hPOField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("HPOFrequency", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public JDBORDisorderListDisorderHPODisorderAssociationListHPODisorderAssociationHPOFrequency[] HPOFrequency
        {
            get
            {
                return this.hPOFrequencyField;
            }
            set
            {
                this.hPOFrequencyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DiagnosticCriteria", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public JDBORDisorderListDisorderHPODisorderAssociationListHPODisorderAssociationDiagnosticCriteria[] DiagnosticCriteria
        {
            get
            {
                return this.diagnosticCriteriaField;
            }
            set
            {
                this.diagnosticCriteriaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class JDBORDisorderListDisorderHPODisorderAssociationListHPODisorderAssociationHPO
    {

        private string hPOIdField;

        private string hPOTermField;

        private string idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HPOId
        {
            get
            {
                return this.hPOIdField;
            }
            set
            {
                this.hPOIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HPOTerm
        {
            get
            {
                return this.hPOTermField;
            }
            set
            {
                this.hPOTermField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class JDBORDisorderListDisorderHPODisorderAssociationListHPODisorderAssociationHPOFrequency
    {

        private string orphaNumberField;

        private Name[] nameField;

        private string idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OrphaNumber
        {
            get
            {
                return this.orphaNumberField;
            }
            set
            {
                this.orphaNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Name", IsNullable = true)]
        public Name[] Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class JDBORDisorderListDisorderHPODisorderAssociationListHPODisorderAssociationDiagnosticCriteria
    {

        private string orphaNumberField;

        private Name[] nameField;

        private string idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OrphaNumber
        {
            get
            {
                return this.orphaNumberField;
            }
            set
            {
                this.orphaNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Name", IsNullable = true)]
        public Name[] Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class NewDataSet
    {

        private object[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("JDBOR", typeof(JDBOR))]
        [System.Xml.Serialization.XmlElementAttribute("Name", typeof(Name), IsNullable = true)]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

}
